const data = [
  {
    project_name: "3D REEL",
    id: "3d-reel",
    desc: `A compilation of my past creative works, including personal and internship projects.`,
    summary: ``,
    media_type: "video",
    media_link: "https://www.youtube.com/embed/A_caxCQkZlc?si=JTEafP2pK5UKZHJJ",
    refs: [],
  },
  {
    project_name: "WAR SCENE",
    id: "war-scene",
    desc: `Personal project intended for lighting and composition practice.`,
    summary: `Heavily inspired by the environment of Dunkirk and the smoke from 
              the short film LE MANS 1955. Project made in Blender.`,
    media_type: "video",
    media_link: "https://www.youtube.com/embed/DvAZ__JEjhk?si=WfkiRNWGjqScJcCu",
    refs: ["city_layout_ref.png", "city_ref.png", "smoke_ref.png"],
  },
  {
    project_name: "FIREWORKS",
    id: "fireworks",
    desc: `Pixar PUP 2024 Project`,
    summary: `This was a houdini project  I made during my PUPs internship at Pixar.  
              We created various different fireworks using a reference image, 
              and rendered them out using Pixar's assets and render system.`,
    media_type: "video",
    media_link: "https://www.youtube.com/embed/eHQU7uij56g?si=Fj8R4Ikdmp3chtCN",
    refs: [],
  },
  {
    project_name: "ANTIQUE ASSET",
    id: "antique-asset",
    desc: `Pixar PUP 2024 Project`,
    summary: `For modeling and shading week, we picked out a fun antique from a store and recreated it on our own style! 
              The modeling was done in Maya, shaded in Flow, and lit in Katana!`,
    media_type: "video",
    media_link: "https://www.youtube.com/embed/1wbv6rPr3CA?si=YmSOeoe2lLIgkUKs",
    refs: ["antique.png"],
  },
  {
    project_name: "RILEY SHOT",
    id: "rily-shot",
    desc: `Pixar PUP 2024 Project`,
    summary: `For lighting week, we focused on lighting this shot from a reference from a movie. 
              I was inspired by the lighting from whiplash, and recreated it here.  
              We mainly used Katana for lighting.`,
    media_type: "video",
    media_link: "https://www.youtube.com/embed/aqcFHufC7vQ?si=3Lp62Epfw5OnIt6W",
    refs: ["whiplash.jpg", "riley.jpg"],
  },
  {
    project_name: "MUSEUM",
    id: "museum",
    desc: `Personal project intended for lighting and composition practice.`,
    summary: `Inspired by a scene from Peaky Blinders, this is a shot of the 
              museum with some creative differences. Project made in Blender.`,
    media_type: "image",
    media_link: "museum.png",
    refs: ["peaky_ref.jpg"],
  },
  {
    project_name: "LOST IN SPACE",
    id: "lost-in-space",
    desc: `A compilation of my past creative works, including personal and internship projects.`,
    summary: `By following a still from the movie Alien, I decided to incorporate my own style into the work! Responsible for layout, lighting, and composition.`,
    media_type: "image",
    media_link: "spacemen.png",
    refs: ["space_men_ref.png"],
  },
  {
    project_name: "OJ & PROSECCO",
    id: "oj-prosecco",
    desc: `Personal project intended for lighting and composition practice.`,
    summary: `My first attempt to combine aspects of motion graphics, 3D modeling, 
              and composition all together into one. One of my favorite projects so far.`,
    media_type: "video",
    media_link: "https://www.youtube.com/embed/Wo1LyaB1W68?si=6VQv5Mn2oAx0cvGm",
    refs: [],
  },
  {
    project_name: "UPSTREAM",
    id: "upstream",
    desc: `Pixar PUP 2024 Group Short Film`,
    summary: `This was our final short film from our PUP 2024 group. I did the sound design, 
              led rendering efforts, and did layout and lighting for various shots.`,
    media_type: "video",
    media_link: "https://www.youtube.com/embed/VISiYMCIBEc?si=nSO7GZ7EJ6LRZuUg",
    refs: [],
  },
  // {
  //   project_name: "RAIN GIRL",
  //   id: "rain-girl",
  //   desc: `Personal project experimenting with lighting, composition, and some shaders..`,
  //   summary: `By following a still from the movie Alien, I decided to incorporate my own style into the work! Responsible for layout, lighting, and composition.`,
  //   media_type: "image",
  //   media_link: "raingirl.png",
  //   refs: ["space_men_ref.png"],
  // },
  
];
